name: Prepare Next Release
on:
  milestone:
    types: [created, edited]

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: contains(github.event.milestone.description, 'Release') && !github.event.milestone.closed
    permissions:
      pull-requests: write
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required for jgit timestamp provider to work
        ref: master    # as not triggered by a commit we need to give explicit reference here
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Update CI Firendly Version Default
      run: mvn -U -Pbuild-individual-bundles -ntp org.eclipse.tycho:tycho-versions-plugin:4.0.0-SNAPSHOT:set-property --non-recursive -Dproperties=releaseVersion -DnewReleaseVersion=${{ github.event.milestone.title }}.0
    - name: Update parent pom version
      run: mvn -U -Pbuild-individual-bundles -ntp org.eclipse.tycho:tycho-versions-plugin:4.0.0-SNAPSHOT:set-parent-version --non-recursive -DnewParentVersion=${{ github.event.milestone.title }}.0-SNAPSHOT
    - name: Create Pull Request for Release ${{ github.event.milestone.title }}
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PR_PAT }} # need to use a PAT due to https://github.com/peter-evans/create-pull-request/issues/48
        commit-message: Prepare Release ${{ github.event.milestone.title }}
        branch: prepare-${{ github.event.milestone.title }}
        title: Prepare Release ${{ github.event.milestone.title }}
        body: A new Release Milstone was created, please review the changes and merge if appropriate.
        delete-branch: true
        reviewers: laeubi
        milestone: ${{ github.event.milestone.number }}
        add-paths: |
            pom.xml
            *.MF
